# Generated by Django 3.2 on 2021-04-16 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
