# Generated by Django 3.2 on 2021-04-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_auto_20210416_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
