# Generated by Django 3.2 on 2021-04-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=12)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.day')),
            ],
        ),
    ]
